# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Cormac Quinn
tagline:          Adventurer, Software Engineer and Tech Enthuast
url:              http://cquinn96.github.io
paginate:         1
baseurl:          /
author:
  name:           Cormac Quinn
  url:            https://twitter.com/cquinn96

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cquinn96/cquinn96.github.io

pages_list:       {'About':'/about','Archive':'/archive'}