# Dependencies
markdown:         redcarpet
highlighter:      pygments   

# Permalinks
permalink:        pretty

# Setup
title:            Cormac Quinn
tagline:          Adventurer, software engineer and tech enthusiast
url:              http://cquinn96.github.io
paginate:         1
baseurl:          /
author:
  name:           Cormac Quinn
  url:            https://twitter.com/cquinn96

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cquinn96/cquinn96.github.io

pages_list:       {'About':'/about','Archive':'/archive'}

gems:             [jekyll-maps]

maps:
  google:
    api_key: ABC